//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("group8bModel", "BookingInfo_Facitliy_FK", "Facility", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Group8b.App_Data.Facility), "BookingInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.BookingInfo), true)]
[assembly: EdmRelationshipAttribute("group8bModel", "BookingInfo_Members_FK", "Members", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Group8b.App_Data.Member), "BookingInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.BookingInfo), true)]
[assembly: EdmRelationshipAttribute("group8bModel", "BookingInfo_Slots_FK", "Slots", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Group8b.App_Data.Slot), "BookingInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.BookingInfo), true)]
[assembly: EdmRelationshipAttribute("group8bModel", "BookingInfo_Sports_FK", "Sports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Group8b.App_Data.Sport), "BookingInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.BookingInfo), true)]
[assembly: EdmRelationshipAttribute("group8bModel", "Facility_Sport_FK", "Sports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Group8b.App_Data.Sport), "Facility", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.Facility), true)]
[assembly: EdmRelationshipAttribute("group8bModel", "Slots_Facility_FK", "Facility", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Group8b.App_Data.Facility), "Slots", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Group8b.App_Data.Slot), true)]

#endregion

namespace Group8b.App_Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class group8bEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new group8bEntities object using the connection string found in the 'group8bEntities' section of the application configuration file.
        /// </summary>
        public group8bEntities() : base("name=group8bEntities", "group8bEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new group8bEntities object.
        /// </summary>
        public group8bEntities(string connectionString) : base(connectionString, "group8bEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new group8bEntities object.
        /// </summary>
        public group8bEntities(EntityConnection connection) : base(connection, "group8bEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BookingInfo> BookingInfoes
        {
            get
            {
                if ((_BookingInfoes == null))
                {
                    _BookingInfoes = base.CreateObjectSet<BookingInfo>("BookingInfoes");
                }
                return _BookingInfoes;
            }
        }
        private ObjectSet<BookingInfo> _BookingInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Facility> Facilities
        {
            get
            {
                if ((_Facilities == null))
                {
                    _Facilities = base.CreateObjectSet<Facility>("Facilities");
                }
                return _Facilities;
            }
        }
        private ObjectSet<Facility> _Facilities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Slot> Slots
        {
            get
            {
                if ((_Slots == null))
                {
                    _Slots = base.CreateObjectSet<Slot>("Slots");
                }
                return _Slots;
            }
        }
        private ObjectSet<Slot> _Slots;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sport> Sports
        {
            get
            {
                if ((_Sports == null))
                {
                    _Sports = base.CreateObjectSet<Sport>("Sports");
                }
                return _Sports;
            }
        }
        private ObjectSet<Sport> _Sports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BookingInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookingInfoes(BookingInfo bookingInfo)
        {
            base.AddObject("BookingInfoes", bookingInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Facilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacilities(Facility facility)
        {
            base.AddObject("Facilities", facility);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Slots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSlots(Slot slot)
        {
            base.AddObject("Slots", slot);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSports(Sport sport)
        {
            base.AddObject("Sports", sport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="BookingInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BookingInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BookingInfo object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="memberID">Initial value of the MemberID property.</param>
        /// <param name="sportID">Initial value of the SportID property.</param>
        /// <param name="facilityID">Initial value of the FacilityID property.</param>
        /// <param name="slotID">Initial value of the SlotID property.</param>
        /// <param name="dateIssue">Initial value of the DateIssue property.</param>
        public static BookingInfo CreateBookingInfo(global::System.Int32 id, global::System.Int32 memberID, global::System.Int32 sportID, global::System.Int32 facilityID, global::System.Int32 slotID, global::System.DateTime dateIssue)
        {
            BookingInfo bookingInfo = new BookingInfo();
            bookingInfo.ID = id;
            bookingInfo.MemberID = memberID;
            bookingInfo.SportID = sportID;
            bookingInfo.FacilityID = facilityID;
            bookingInfo.SlotID = slotID;
            bookingInfo.DateIssue = dateIssue;
            return bookingInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                OnMemberIDChanging(value);
                ReportPropertyChanging("MemberID");
                _MemberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MemberID");
                OnMemberIDChanged();
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SportID
        {
            get
            {
                return _SportID;
            }
            set
            {
                OnSportIDChanging(value);
                ReportPropertyChanging("SportID");
                _SportID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SportID");
                OnSportIDChanged();
            }
        }
        private global::System.Int32 _SportID;
        partial void OnSportIDChanging(global::System.Int32 value);
        partial void OnSportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FacilityID
        {
            get
            {
                return _FacilityID;
            }
            set
            {
                OnFacilityIDChanging(value);
                ReportPropertyChanging("FacilityID");
                _FacilityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacilityID");
                OnFacilityIDChanged();
            }
        }
        private global::System.Int32 _FacilityID;
        partial void OnFacilityIDChanging(global::System.Int32 value);
        partial void OnFacilityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SlotID
        {
            get
            {
                return _SlotID;
            }
            set
            {
                OnSlotIDChanging(value);
                ReportPropertyChanging("SlotID");
                _SlotID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlotID");
                OnSlotIDChanged();
            }
        }
        private global::System.Int32 _SlotID;
        partial void OnSlotIDChanging(global::System.Int32 value);
        partial void OnSlotIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateIssue
        {
            get
            {
                return _DateIssue;
            }
            set
            {
                OnDateIssueChanging(value);
                ReportPropertyChanging("DateIssue");
                _DateIssue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateIssue");
                OnDateIssueChanged();
            }
        }
        private global::System.DateTime _DateIssue;
        partial void OnDateIssueChanging(global::System.DateTime value);
        partial void OnDateIssueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Facitliy_FK", "Facility")]
        public Facility Facility
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.BookingInfo_Facitliy_FK", "Facility").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.BookingInfo_Facitliy_FK", "Facility").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Facility> FacilityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.BookingInfo_Facitliy_FK", "Facility");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Facility>("group8bModel.BookingInfo_Facitliy_FK", "Facility", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Members_FK", "Members")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("group8bModel.BookingInfo_Members_FK", "Members").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("group8bModel.BookingInfo_Members_FK", "Members").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("group8bModel.BookingInfo_Members_FK", "Members");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("group8bModel.BookingInfo_Members_FK", "Members", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Slots_FK", "Slots")]
        public Slot Slot
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Slot>("group8bModel.BookingInfo_Slots_FK", "Slots").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Slot>("group8bModel.BookingInfo_Slots_FK", "Slots").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Slot> SlotReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Slot>("group8bModel.BookingInfo_Slots_FK", "Slots");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Slot>("group8bModel.BookingInfo_Slots_FK", "Slots", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Sports_FK", "Sports")]
        public Sport Sport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.BookingInfo_Sports_FK", "Sports").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.BookingInfo_Sports_FK", "Sports").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sport> SportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.BookingInfo_Sports_FK", "Sports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sport>("group8bModel.BookingInfo_Sports_FK", "Sports", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="Facility")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Facility : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Facility object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="sportID">Initial value of the SportID property.</param>
        /// <param name="courtCode">Initial value of the CourtCode property.</param>
        /// <param name="courtName">Initial value of the CourtName property.</param>
        public static Facility CreateFacility(global::System.Int32 id, global::System.Int32 sportID, global::System.String courtCode, global::System.String courtName)
        {
            Facility facility = new Facility();
            facility.ID = id;
            facility.SportID = sportID;
            facility.CourtCode = courtCode;
            facility.CourtName = courtName;
            return facility;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SportID
        {
            get
            {
                return _SportID;
            }
            set
            {
                OnSportIDChanging(value);
                ReportPropertyChanging("SportID");
                _SportID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SportID");
                OnSportIDChanged();
            }
        }
        private global::System.Int32 _SportID;
        partial void OnSportIDChanging(global::System.Int32 value);
        partial void OnSportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourtCode
        {
            get
            {
                return _CourtCode;
            }
            set
            {
                OnCourtCodeChanging(value);
                ReportPropertyChanging("CourtCode");
                _CourtCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CourtCode");
                OnCourtCodeChanged();
            }
        }
        private global::System.String _CourtCode;
        partial void OnCourtCodeChanging(global::System.String value);
        partial void OnCourtCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CourtName
        {
            get
            {
                return _CourtName;
            }
            set
            {
                OnCourtNameChanging(value);
                ReportPropertyChanging("CourtName");
                _CourtName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CourtName");
                OnCourtNameChanged();
            }
        }
        private global::System.String _CourtName;
        partial void OnCourtNameChanging(global::System.String value);
        partial void OnCourtNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Facitliy_FK", "BookingInfo")]
        public EntityCollection<BookingInfo> BookingInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Facitliy_FK", "BookingInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Facitliy_FK", "BookingInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "Facility_Sport_FK", "Sports")]
        public Sport Sport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.Facility_Sport_FK", "Sports").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.Facility_Sport_FK", "Sports").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Sport> SportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Sport>("group8bModel.Facility_Sport_FK", "Sports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Sport>("group8bModel.Facility_Sport_FK", "Sports", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "Slots_Facility_FK", "Slots")]
        public EntityCollection<Slot> Slots
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Slot>("group8bModel.Slots_Facility_FK", "Slots");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Slot>("group8bModel.Slots_Facility_FK", "Slots", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="phoneNumber">Initial value of the PhoneNumber property.</param>
        public static Member CreateMember(global::System.Int32 id, global::System.String name, global::System.String phoneNumber)
        {
            Member member = new Member();
            member.ID = id;
            member.Name = name;
            member.PhoneNumber = phoneNumber;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Members_FK", "BookingInfo")]
        public EntityCollection<BookingInfo> BookingInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Members_FK", "BookingInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Members_FK", "BookingInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="Slot")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Slot : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Slot object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="timeFrom">Initial value of the TimeFrom property.</param>
        /// <param name="timeTo">Initial value of the TimeTo property.</param>
        public static Slot CreateSlot(global::System.Int32 id, global::System.TimeSpan timeFrom, global::System.TimeSpan timeTo)
        {
            Slot slot = new Slot();
            slot.ID = id;
            slot.TimeFrom = timeFrom;
            slot.TimeTo = timeTo;
            return slot;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FacilityID
        {
            get
            {
                return _FacilityID;
            }
            set
            {
                OnFacilityIDChanging(value);
                ReportPropertyChanging("FacilityID");
                _FacilityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacilityID");
                OnFacilityIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FacilityID;
        partial void OnFacilityIDChanging(Nullable<global::System.Int32> value);
        partial void OnFacilityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeFrom
        {
            get
            {
                return _TimeFrom;
            }
            set
            {
                OnTimeFromChanging(value);
                ReportPropertyChanging("TimeFrom");
                _TimeFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeFrom");
                OnTimeFromChanged();
            }
        }
        private global::System.TimeSpan _TimeFrom;
        partial void OnTimeFromChanging(global::System.TimeSpan value);
        partial void OnTimeFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan TimeTo
        {
            get
            {
                return _TimeTo;
            }
            set
            {
                OnTimeToChanging(value);
                ReportPropertyChanging("TimeTo");
                _TimeTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeTo");
                OnTimeToChanged();
            }
        }
        private global::System.TimeSpan _TimeTo;
        partial void OnTimeToChanging(global::System.TimeSpan value);
        partial void OnTimeToChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Slots_FK", "BookingInfo")]
        public EntityCollection<BookingInfo> BookingInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Slots_FK", "BookingInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Slots_FK", "BookingInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "Slots_Facility_FK", "Facility")]
        public Facility Facility
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.Slots_Facility_FK", "Facility").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.Slots_Facility_FK", "Facility").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Facility> FacilityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Facility>("group8bModel.Slots_Facility_FK", "Facility");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Facility>("group8bModel.Slots_Facility_FK", "Facility", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="Sport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sport object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Sport CreateSport(global::System.Int32 id, global::System.String name)
        {
            Sport sport = new Sport();
            sport.ID = id;
            sport.Name = name;
            return sport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SportType
        {
            get
            {
                return _SportType;
            }
            set
            {
                OnSportTypeChanging(value);
                ReportPropertyChanging("SportType");
                _SportType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SportType");
                OnSportTypeChanged();
            }
        }
        private global::System.String _SportType;
        partial void OnSportTypeChanging(global::System.String value);
        partial void OnSportTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private Nullable<global::System.Int16> _Size;
        partial void OnSizeChanging(Nullable<global::System.Int16> value);
        partial void OnSizeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "BookingInfo_Sports_FK", "BookingInfo")]
        public EntityCollection<BookingInfo> BookingInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Sports_FK", "BookingInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BookingInfo>("group8bModel.BookingInfo_Sports_FK", "BookingInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("group8bModel", "Facility_Sport_FK", "Facility")]
        public EntityCollection<Facility> Facilities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Facility>("group8bModel.Facility_Sport_FK", "Facility");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Facility>("group8bModel.Facility_Sport_FK", "Facility", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="group8bModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="confirmPassword">Initial value of the ConfirmPassword property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String name, global::System.String password, global::System.String confirmPassword)
        {
            User user = new User();
            user.ID = id;
            user.Name = name;
            user.Password = password;
            user.ConfirmPassword = confirmPassword;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConfirmPassword
        {
            get
            {
                return _ConfirmPassword;
            }
            set
            {
                OnConfirmPasswordChanging(value);
                ReportPropertyChanging("ConfirmPassword");
                _ConfirmPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConfirmPassword");
                OnConfirmPasswordChanged();
            }
        }
        private global::System.String _ConfirmPassword;
        partial void OnConfirmPasswordChanging(global::System.String value);
        partial void OnConfirmPasswordChanged();

        #endregion

    
    }

    #endregion

    
}
